# https://developers.home-assistant.io/docs/add-ons/configuration
name: OpenObserve Log Shipper
version: "0.1.0"
slug: openobserve_log_shipper
description: Tail Home Assistant log files and forward them to OpenObserve.
url: "https://github.com/Shaffer-Softworks/home-assistant-openobserve-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
hassio_api: false
homeassistant_api: false
map:
  - config:ro
options:
  openobserve_url: ""
  openobserve_username: ""
  openobserve_password: ""
  log_path: "/config/home-assistant.log"
schema:
  openobserve_url: str
  openobserve_username: str
  openobserve_password: password
  log_path: str
